/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as LaborRouteImport } from './routes/labor'
import { Route as LoansRouteImport } from './routes/loans'
import { Route as MachineryRouteImport } from './routes/machinery'
import { Route as MarketRouteImport } from './routes/market'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RecordsRouteImport } from './routes/records'
import { Route as RiskRouteImport } from './routes/risk'
import { Route as SchemesRouteImport } from './routes/schemes'
import { Route as SignoutRouteImport } from './routes/signout'
import { Route as SoilRouteImport } from './routes/soil'
import { Route as SubsidiesRouteImport } from './routes/subsidies'
import { Route as SupportRouteImport } from './routes/support'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as WaterRouteImport } from './routes/water'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const LaborRoute = LaborRouteImport.update({
  id: '/labor',
  path: '/labor',
  getParentRoute: () => rootRouteImport,
} as any)
const LoansRoute = LoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => rootRouteImport,
} as any)
const MachineryRoute = MachineryRouteImport.update({
  id: '/machinery',
  path: '/machinery',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsRoute = RecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskRoute = RiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemesRoute = SchemesRouteImport.update({
  id: '/schemes',
  path: '/schemes',
  getParentRoute: () => rootRouteImport,
} as any)
const SignoutRoute = SignoutRouteImport.update({
  id: '/signout',
  path: '/signout',
  getParentRoute: () => rootRouteImport,
} as any)
const SoilRoute = SoilRouteImport.update({
  id: '/soil',
  path: '/soil',
  getParentRoute: () => rootRouteImport,
} as any)
const SubsidiesRoute = SubsidiesRouteImport.update({
  id: '/subsidies',
  path: '/subsidies',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const WaterRoute = WaterRouteImport.update({
  id: '/water',
  path: '/water',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/community': typeof CommunityRoute
  '/labor': typeof LaborRoute
  '/loans': typeof LoansRoute
  '/machinery': typeof MachineryRoute
  '/market': typeof MarketRoute
  '/profile': typeof ProfileRoute
  '/records': typeof RecordsRoute
  '/risk': typeof RiskRoute
  '/schemes': typeof SchemesRoute
  '/signout': typeof SignoutRoute
  '/soil': typeof SoilRoute
  '/subsidies': typeof SubsidiesRoute
  '/support': typeof SupportRoute
  '/wallet': typeof WalletRoute
  '/water': typeof WaterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/community': typeof CommunityRoute
  '/labor': typeof LaborRoute
  '/loans': typeof LoansRoute
  '/machinery': typeof MachineryRoute
  '/market': typeof MarketRoute
  '/profile': typeof ProfileRoute
  '/records': typeof RecordsRoute
  '/risk': typeof RiskRoute
  '/schemes': typeof SchemesRoute
  '/signout': typeof SignoutRoute
  '/soil': typeof SoilRoute
  '/subsidies': typeof SubsidiesRoute
  '/support': typeof SupportRoute
  '/wallet': typeof WalletRoute
  '/water': typeof WaterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/community': typeof CommunityRoute
  '/labor': typeof LaborRoute
  '/loans': typeof LoansRoute
  '/machinery': typeof MachineryRoute
  '/market': typeof MarketRoute
  '/profile': typeof ProfileRoute
  '/records': typeof RecordsRoute
  '/risk': typeof RiskRoute
  '/schemes': typeof SchemesRoute
  '/signout': typeof SignoutRoute
  '/soil': typeof SoilRoute
  '/subsidies': typeof SubsidiesRoute
  '/support': typeof SupportRoute
  '/wallet': typeof WalletRoute
  '/water': typeof WaterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/community'
    | '/labor'
    | '/loans'
    | '/machinery'
    | '/market'
    | '/profile'
    | '/records'
    | '/risk'
    | '/schemes'
    | '/signout'
    | '/soil'
    | '/subsidies'
    | '/support'
    | '/wallet'
    | '/water'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/community'
    | '/labor'
    | '/loans'
    | '/machinery'
    | '/market'
    | '/profile'
    | '/records'
    | '/risk'
    | '/schemes'
    | '/signout'
    | '/soil'
    | '/subsidies'
    | '/support'
    | '/wallet'
    | '/water'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/community'
    | '/labor'
    | '/loans'
    | '/machinery'
    | '/market'
    | '/profile'
    | '/records'
    | '/risk'
    | '/schemes'
    | '/signout'
    | '/soil'
    | '/subsidies'
    | '/support'
    | '/wallet'
    | '/water'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  CommunityRoute: typeof CommunityRoute
  LaborRoute: typeof LaborRoute
  LoansRoute: typeof LoansRoute
  MachineryRoute: typeof MachineryRoute
  MarketRoute: typeof MarketRoute
  ProfileRoute: typeof ProfileRoute
  RecordsRoute: typeof RecordsRoute
  RiskRoute: typeof RiskRoute
  SchemesRoute: typeof SchemesRoute
  SignoutRoute: typeof SignoutRoute
  SoilRoute: typeof SoilRoute
  SubsidiesRoute: typeof SubsidiesRoute
  SupportRoute: typeof SupportRoute
  WalletRoute: typeof WalletRoute
  WaterRoute: typeof WaterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labor': {
      id: '/labor'
      path: '/labor'
      fullPath: '/labor'
      preLoaderRoute: typeof LaborRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loans': {
      id: '/loans'
      path: '/loans'
      fullPath: '/loans'
      preLoaderRoute: typeof LoansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/machinery': {
      id: '/machinery'
      path: '/machinery'
      fullPath: '/machinery'
      preLoaderRoute: typeof MachineryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records': {
      id: '/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof RecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk': {
      id: '/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof RiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schemes': {
      id: '/schemes'
      path: '/schemes'
      fullPath: '/schemes'
      preLoaderRoute: typeof SchemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signout': {
      id: '/signout'
      path: '/signout'
      fullPath: '/signout'
      preLoaderRoute: typeof SignoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soil': {
      id: '/soil'
      path: '/soil'
      fullPath: '/soil'
      preLoaderRoute: typeof SoilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subsidies': {
      id: '/subsidies'
      path: '/subsidies'
      fullPath: '/subsidies'
      preLoaderRoute: typeof SubsidiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/water': {
      id: '/water'
      path: '/water'
      fullPath: '/water'
      preLoaderRoute: typeof WaterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  CommunityRoute: CommunityRoute,
  LaborRoute: LaborRoute,
  LoansRoute: LoansRoute,
  MachineryRoute: MachineryRoute,
  MarketRoute: MarketRoute,
  ProfileRoute: ProfileRoute,
  RecordsRoute: RecordsRoute,
  RiskRoute: RiskRoute,
  SchemesRoute: SchemesRoute,
  SignoutRoute: SignoutRoute,
  SoilRoute: SoilRoute,
  SubsidiesRoute: SubsidiesRoute,
  SupportRoute: SupportRoute,
  WalletRoute: WalletRoute,
  WaterRoute: WaterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
